#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xF3599FF828C67298 (nisse@lysator.liu.se)
#
Name     : compat-nettle-soname6
Version  : 3.4.1
Release  : 40
URL      : https://mirrors.kernel.org/gnu/nettle/nettle-3.4.1.tar.gz
Source0  : https://mirrors.kernel.org/gnu/nettle/nettle-3.4.1.tar.gz
Source99 : https://mirrors.kernel.org/gnu/nettle/nettle-3.4.1.tar.gz.sig
Summary  : Nettle low-level cryptographic library (symmetric algorithms)
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-3.0
Requires: compat-nettle-soname6-bin = %{version}-%{release}
Requires: compat-nettle-soname6-lib = %{version}-%{release}
Requires: compat-nettle-soname6-license = %{version}-%{release}
Requires: p11-kit
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gmp-dev
BuildRequires : gmp-dev32
BuildRequires : gmp-lib32
BuildRequires : openssl-dev
BuildRequires : p11-kit
BuildRequires : texinfo

%description
What is GNU Nettle? A quote from the introduction in the Nettle Manual:
Nettle is a cryptographic library that is designed to fit easily in more
or less any context: In crypto toolkits for object-oriented languages
(C++, Python, Pike, ...), in applications like LSH or GNUPG, or even in
kernel space. In most contexts, you need more than the basic
cryptographic algorithms, you also need some way to keep track of available
algorithms, their properties and variants. You often have some algorithm
selection process, often dictated by a protocol you want to implement.

And as the requirements of applications differ in subtle and not so
subtle ways, an API that fits one application well can be a pain to use
in a different context. And that is why there are so many different
cryptographic libraries around.

Nettle tries to avoid this problem by doing one thing, the low-level
crypto stuff, and providing a simple but general interface to it.
In particular, Nettle doesn't do algorithm selection. It doesn't do
memory allocation. It doesn't do any I/O.

The idea is that one can build several application and context specific
interfaces on top of Nettle, and share the code, test cases, benchmarks,
documentation, etc. Examples are the Nettle module for the Pike
language, and LSH, which both use an object-oriented abstraction on top
of the library.

%package bin
Summary: bin components for the compat-nettle-soname6 package.
Group: Binaries
Requires: compat-nettle-soname6-license = %{version}-%{release}

%description bin
bin components for the compat-nettle-soname6 package.


%package dev
Summary: dev components for the compat-nettle-soname6 package.
Group: Development
Requires: compat-nettle-soname6-lib = %{version}-%{release}
Requires: compat-nettle-soname6-bin = %{version}-%{release}
Provides: compat-nettle-soname6-devel = %{version}-%{release}
Requires: compat-nettle-soname6 = %{version}-%{release}
Requires: compat-nettle-soname6 = %{version}-%{release}

%description dev
dev components for the compat-nettle-soname6 package.


%package dev32
Summary: dev32 components for the compat-nettle-soname6 package.
Group: Default
Requires: compat-nettle-soname6-lib32 = %{version}-%{release}
Requires: compat-nettle-soname6-bin = %{version}-%{release}
Requires: compat-nettle-soname6-dev = %{version}-%{release}

%description dev32
dev32 components for the compat-nettle-soname6 package.


%package doc
Summary: doc components for the compat-nettle-soname6 package.
Group: Documentation

%description doc
doc components for the compat-nettle-soname6 package.


%package lib
Summary: lib components for the compat-nettle-soname6 package.
Group: Libraries
Requires: compat-nettle-soname6-license = %{version}-%{release}

%description lib
lib components for the compat-nettle-soname6 package.


%package lib32
Summary: lib32 components for the compat-nettle-soname6 package.
Group: Default
Requires: compat-nettle-soname6-license = %{version}-%{release}

%description lib32
lib32 components for the compat-nettle-soname6 package.


%package license
Summary: license components for the compat-nettle-soname6 package.
Group: Default

%description license
license components for the compat-nettle-soname6 package.


%prep
%setup -q -n nettle-3.4.1
pushd ..
cp -a nettle-3.4.1 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1562053329
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure --disable-static --disable-openssl --enable-shared --enable-static  --enable-x86-aesni
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32"
%configure --disable-static --disable-openssl --enable-shared --enable-static  --enable-x86-aesni   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make -C testsuite check
make -C ../build32/testsuite check

%install
export SOURCE_DATE_EPOCH=1562053329
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-nettle-soname6
cp COPYING.LESSERv3 %{buildroot}/usr/share/package-licenses/compat-nettle-soname6/COPYING.LESSERv3
cp COPYINGv2 %{buildroot}/usr/share/package-licenses/compat-nettle-soname6/COPYINGv2
cp COPYINGv3 %{buildroot}/usr/share/package-licenses/compat-nettle-soname6/COPYINGv3
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/nettle-hash
%exclude /usr/bin/nettle-lfib-stream
%exclude /usr/bin/nettle-pbkdf2
%exclude /usr/bin/pkcs1-conv
%exclude /usr/bin/sexp-conv

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/nettle/aes.h
%exclude /usr/include/nettle/arcfour.h
%exclude /usr/include/nettle/arctwo.h
%exclude /usr/include/nettle/asn1.h
%exclude /usr/include/nettle/base16.h
%exclude /usr/include/nettle/base64.h
%exclude /usr/include/nettle/bignum.h
%exclude /usr/include/nettle/blowfish.h
%exclude /usr/include/nettle/buffer.h
%exclude /usr/include/nettle/camellia.h
%exclude /usr/include/nettle/cast128.h
%exclude /usr/include/nettle/cbc.h
%exclude /usr/include/nettle/ccm.h
%exclude /usr/include/nettle/cfb.h
%exclude /usr/include/nettle/chacha-poly1305.h
%exclude /usr/include/nettle/chacha.h
%exclude /usr/include/nettle/ctr.h
%exclude /usr/include/nettle/curve25519.h
%exclude /usr/include/nettle/des-compat.h
%exclude /usr/include/nettle/des.h
%exclude /usr/include/nettle/dsa-compat.h
%exclude /usr/include/nettle/dsa.h
%exclude /usr/include/nettle/eax.h
%exclude /usr/include/nettle/ecc-curve.h
%exclude /usr/include/nettle/ecc.h
%exclude /usr/include/nettle/ecdsa.h
%exclude /usr/include/nettle/eddsa.h
%exclude /usr/include/nettle/gcm.h
%exclude /usr/include/nettle/gosthash94.h
%exclude /usr/include/nettle/hkdf.h
%exclude /usr/include/nettle/hmac.h
%exclude /usr/include/nettle/knuth-lfib.h
%exclude /usr/include/nettle/macros.h
%exclude /usr/include/nettle/md2.h
%exclude /usr/include/nettle/md4.h
%exclude /usr/include/nettle/md5-compat.h
%exclude /usr/include/nettle/md5.h
%exclude /usr/include/nettle/memops.h
%exclude /usr/include/nettle/memxor.h
%exclude /usr/include/nettle/nettle-meta.h
%exclude /usr/include/nettle/nettle-stdint.h
%exclude /usr/include/nettle/nettle-types.h
%exclude /usr/include/nettle/pbkdf2.h
%exclude /usr/include/nettle/pgp.h
%exclude /usr/include/nettle/pkcs1.h
%exclude /usr/include/nettle/poly1305.h
%exclude /usr/include/nettle/pss-mgf1.h
%exclude /usr/include/nettle/pss.h
%exclude /usr/include/nettle/realloc.h
%exclude /usr/include/nettle/ripemd160.h
%exclude /usr/include/nettle/rsa.h
%exclude /usr/include/nettle/salsa20.h
%exclude /usr/include/nettle/serpent.h
%exclude /usr/include/nettle/sexp.h
%exclude /usr/include/nettle/sha.h
%exclude /usr/include/nettle/sha1.h
%exclude /usr/include/nettle/sha2.h
%exclude /usr/include/nettle/sha3.h
%exclude /usr/include/nettle/twofish.h
%exclude /usr/include/nettle/umac.h
%exclude /usr/include/nettle/version.h
%exclude /usr/include/nettle/yarrow.h
%exclude /usr/lib64/libhogweed.so
%exclude /usr/lib64/libnettle.so
%exclude /usr/lib64/pkgconfig/hogweed.pc
%exclude /usr/lib64/pkgconfig/nettle.pc

%files dev32
%defattr(-,root,root,-)
%exclude /usr/lib32/libhogweed.so
%exclude /usr/lib32/libnettle.so
%exclude /usr/lib32/pkgconfig/32hogweed.pc
%exclude /usr/lib32/pkgconfig/32nettle.pc
%exclude /usr/lib32/pkgconfig/hogweed.pc
%exclude /usr/lib32/pkgconfig/nettle.pc

%files doc
%defattr(0644,root,root,0755)
%exclude /usr/share/info/nettle.info

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhogweed.so.4
/usr/lib64/libhogweed.so.4.5
/usr/lib64/libnettle.so.6
/usr/lib64/libnettle.so.6.5

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libhogweed.so.4
/usr/lib32/libhogweed.so.4.5
/usr/lib32/libnettle.so.6
/usr/lib32/libnettle.so.6.5

%files license
%defattr(0644,root,root,0755)
%exclude /usr/share/package-licenses/compat-nettle-soname6/COPYING.LESSERv3
%exclude /usr/share/package-licenses/compat-nettle-soname6/COPYINGv2
%exclude /usr/share/package-licenses/compat-nettle-soname6/COPYINGv3
